### PR TITLE
try some kind of theme

### PR DESCRIPTION
**Pull request by thedaniel**
after seeing @bvhme's pull request (#1) i wonder if this should be more pink? just a jekyll template i grabbed from internet

cc @crisdobbins for thoughts

screen shot 2016-01-17 at 6 40 05 pm

### CODE REVIEW

**Comment by bvhme** [comment]
I like it but I feel it needs more content, what is there for us to contentualise?

**Comment by bvhme** [comment]
Also my version can just serve as a placeholder, I think the more serious 'Research Institute' look is also a good direction.

**Comment by thedaniel** [comment]
I have so much content in my brain that i've been talking out with people in person, and i'd love to fill you in but I have to go for drinks RIGHT NOW.

**Comment by thedaniel** [comment]
I'm going to merge this, even though the content isn't written, to feel like something is shipping and move this forward.

**Pull request merged**
